language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
# install: "pip install -r requirements.txt"
install: "pip install bs4"
# command to run tests
script: python audit.py phone Bishkek_sample.osm
